### ISSUE TITLE
docker部署镜像建议

### ISSUE THREAD

**Issue by xsbai93** [javahuang/SurveyKing#14]
【问题】现docker镜像部署时，由于数据库文件surveyking.mv.db在根目录，无法挂载至宿主机
【方法】建议镜像内文件部署在surveyking子文件夹下，例如/surveyking/config，/surveyking/db，/surveyking/file，/surveyking/logs等，统一规范方便目录挂载

**Comment by javahuang** [comment]
谢谢建议，下个版本完善

**Comment by javahuang** [comment]
已push 新版本
