### ISSUE TITLE
NEW BUG

### ISSUE THREAD

**Issue by UYSAUIYO** [javahuang/SurveyKing#22]
Google Chrome 版本 110.0.5481.77（正式版本） （64 位）

   在设置问卷的标题，出现任意字符输入时发生输入单个字符后出现 标题编辑处失去焦点，并且无法再次输入文字。
只再次点击编辑才能继续输入字符，且只能输入一个文字，然后继续失去焦点，以此循环。
![Uploading CPT2302092232-862x176.gif…]()

**Comment by javahuang** [comment]
已修复
