### ISSUE TITLE
idea 包加载不全

### ISSUE THREAD

**Issue by ABC15859888** [javahuang/SurveyKing#24]
请大佬指导下这种情况如何处理

![image](https://user-images.githubusercontent.com/38815757/225548611-c7de0e5c-53f3-462f-b32e-86a61a3192e5.png)

**Comment by ABC15859888** [comment]
> 请大佬指导下这种情况如何处理
> 
> ![image](https://user-images.githubusercontent.com/38815757/225548611-c7de0e5c-53f3-462f-b32e-86a61a3192e5.png)

![image](https://user-images.githubusercontent.com/38815757/225548999-304a2fe0-b097-46ef-bac0-691f6001760e.png)

**Comment by javahuang** [comment]
导入 server 根目录
