### ISSUE TITLE
There is a logout logic vulnerability in the background

### ISSUE THREAD

**Issue by l2sec** [javahuang/SurveyKing#7]
Version：v0.2.0
First, log in to the background normally and send query requests. Pay attention to cookies

![image](https://user-images.githubusercontent.com/59214809/154828714-a2ce6ea2-5110-4866-a3aa-fc775884faa1.png)
Then click the exit login button. At this time, the back-end code does not delete the user's session, but just jumps to the login page. You can see that the requested data can still be obtained normally with the previous cookie. Then the attacker can log in to the system again with the help of the browser cache when the user exits.

![image](https://user-images.githubusercontent.com/59214809/154828764-ff2d6b80-69f7-469b-9387-0b9fca22eba3.png)
Repair suggestion: when exiting the login, delete the user's session first, and then jump to the login page.

**Comment by javahuang** [comment]
@l2sec  thanks, fixed https://github.com/javahuang/SurveyKing/commit/b637feda118dd5a6db142b2705b2d55ffbfb4b48

The backend uses JWT. Currently, I don't want to use additional storage, such as a blacklist mechanism, just delete the token cookie from server now.
