### ISSUE TITLE
v2ex来的

### ISSUE THREAD

**Issue by meetingxu** [javahuang/SurveyKing#8]
啥时候前端开源一下呗，我想部署下公司内用用，替换一下问卷星。

谢谢🙏

**Comment by javahuang** [comment]
> 

@meetingxu 等完善之后会部门开源，现在也可以直接部署，有啥不能满足您的需要的吗？

**Comment by meetingxu** [comment]
我想给改改logo啥的

**Comment by javahuang** [comment]
> 
![Jietu20220302-153221](https://user-images.githubusercontent.com/3992393/156315374-7fd62a98-9555-48a3-8b87-6416e20ca3e2.jpg)

@meetingxu  现在这个版本支持改 logo 和项目名这些的
